version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  runtime = "nodejs"
  environment = ["browser"]
  module_system = "es6"
  jsx = true
  typescript = true
  plugins = ["react"]

[[analyzers]]
name = "secrets"
enabled = true
